/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "DrumStripeHandler.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class JuceDemoPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                            public SliderListener,
                                            public Timer
{
public:
    JuceDemoPluginAudioProcessorEditor (JuceDemoPluginAudioProcessor&);
    ~JuceDemoPluginAudioProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider*) override;
    void sliderDragStarted  (Slider*) override;
    void sliderDragEnded    (Slider*) override;
    
    MidiKeyboardComponent midiKeyboard;
    Label infoLabel, gainLabel, delayLabel, balanceLabel, rmsR_Label,rmsL_Label ;
    Slider gainSlider ,balanceSlider, delaySlider;
    
    void setDrumStripeEditor(); // set editor into drumstripes
    void refreshDrumStripeView();
    
    JuceDemoPluginAudioProcessor& getProcessor() const
    {
        return static_cast<JuceDemoPluginAudioProcessor&> (processor);
    }
    
    void setInfoMessage(String,bool);
    String getInfoMessage();
    
private:
   
    
    ScopedPointer<ResizableCornerComponent> resizer;
    ComponentBoundsConstrainer resizeLimits;

    AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;
    
    TimeSliceThread thread;
    DirectoryContentsList directoryContentsList;
    
    //DrumStripeHandler editor;
    
    
    std::vector<DrumStripeHandler*> drumStripes;
    
    //AudioProcessorGraph audioProcessorGraph;
    
    //AudioDeviceManager& fDeviceManager;

    //==============================================================================
    

    AudioProcessorParameter* getParameterFromSlider (const Slider*) const;

    void displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos);
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
