/*
 ==============================================================================
 
 This file was auto-generated by the Jucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
 */


#include "../JuceLibraryCode/JuceHeader.h"

#include <vector>
#include <string>
#include <iostream>
#include <string.h>
#include <stdlib.h>
#include <fstream>


void debugLog(String debugTxt);
void debugLog(String debugTxt, bool separator );