/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include <JuceHeader.h>


#include "utils.h"

using namespace std;

const bool debugMode = true;

void debugLog(juce::String debugTxt, bool separator){

    juce::String WithSeparator = "\n ----------------------" + debugTxt +"--------------------------- \n";
    
    debugLog(WithSeparator);
}


void debugLog(juce::String debugTxt){
    //creating log file
    #if DEBUG
        juce::String timeStamp = date::format("%F %T", std::chrono::system_clock::now());
        
        debugTxt = timeStamp +": "+debugTxt;

        ofstream logfile;
        logfile.open ("/Users/oliou/Desktop/debug.txt", std::ios::app);
        logfile << debugTxt << "\n";
        logfile.close();
    #endif
}
