/*
 ==============================================================================
 
 This file was auto-generated by the Jucer!
 
 It contains the basic startup code for a Juce application.
 
 ==============================================================================
 */


//#include "../JuceLibraryCode/JuceHeader.h"

#include <JuceHeader.h>

#include <vector>
#include <string>
#include <iostream>
#include <string.h>
#include <stdlib.h>
#include <fstream>

#include "date.h"



void debugLog(juce::String debugTxt);
void debugLog(juce::String debugTxt, bool separator );
